export const data = [
  {
    key: "1",
    project: "Web Development Project",
    client: "PT. Matahari",
    task: "Membuat desain konfigurasi pengguna",
    deadline: "19/12/2023",
    assignTo: "John De",
    createdBy: "Robert Pattinson",
    status: "in-progress",
  },
  {
    key: "2",
    project: "Web Development Project",
    client: "PT. Matahari",
    task: "Antarmuka konfigurasi pengguna",
    deadline: "19/12/2023",
    assignTo: "Jacob Anderson",
    createdBy: "Robert Pattinson",
    status: "done",
  },
  {
    key: "3",
    project: "Web Development Project",
    client: "PT. Matahari",
    task: "Create table user",
    deadline: "19/12/2023",
    assignTo: "Tamara Sandrina",
    createdBy: "Robert Pattinson",
    status: "review",
  },
  {
    key: "4",
    project: "Web Development Project",
    client: "PT. Matahari",
    task: "Antarmuka konfigurasi pengguna",
    deadline: "19/12/2023",
    assignTo: "John De",
    createdBy: "Robert Pattinson",
    status: "cancel",
  },
  {
    key: "5",
    project: "Web Development Project",
    client: "PT. Matahari",
    task: "Membuat desain konfigurasi pengguna",
    deadline: "19/12/2023",
    assignTo: "Tamara Sandrina",
    createdBy: "Robert Pattinson",
    status: "open",
  }
]